version: 1.0.{build}
image: Visual Studio 2017
platform: Any CPU
clone_folder: C:\projects\
build:
  project: RLE.sln
  verbosity: minimal
test_script:
- cmd: >-
    mkdir Results
    
    cd bin\Debug\
    
    RLE p ..\..\Test\unpacked.nes ..\..\Results\packed.nes
    
    RLE u ..\..\Test\packed.nes ..\..\Results\unpacked.nes
    
    FC /B ..\..\Test\unpacked.nes ..\..\Results\unpacked.nes
    
    FC /B ..\..\Test\packed.nes ..\..\Results\packed.nes
